<a href="https://colab.research.google.com/github/darshan-jain/19CSE305/blob/main/ML_LAB2_CSEB_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **19CSE305: MACHINE LEARNING LAB 2**

PYTHON BASICS : EXCERCISES

ROLL NUMBER: CB.EN.U4CSE19126
Name: M.Darshan

In [ ]:
PYTHON BASIC EXCERSISE

1) Get the values P,t,R from user and calculate compound interest.Formula to calculate compound interest annually is given by: 
        A = P(1 + R/100) t
        CI= A – P
        Input : Principle, Time, Rate
        Output : Compound Interest
2) Given a list of strings( Entered by the user), write program to get a percentage share of each word in the strings list.
          percentage := (Occurrence of a word / Total words) * 100
3)Check if  the binary representation of a number is Palindrome or not. Given an integer ‘n’( Entered by the user), write a Python function that returns true if binary representation of x is palindrome else return false.
4)Write a program to check if all digits of a number divide it. Given a number n( Entered by the user), find whether all digits of n divide it or not.
5)Given a list of numbers ( Entered by the user), write a program to find the second largest number in that list.
        Input: [1, 2, 3, 4 ,5]
        Output: 4

NUMPY BASIC EXCERSISE

1) Create a 3D array of shape 4*5*2 that contains random decimal numbers between 1 and 10.
2) Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
3) Given a NumPy array of temperature values, convert the values of Centigrade degrees into Fahrenheit degrees. 
4) Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
5) Write a NumPy program to extract third and second elements of the first and second rows from a given (3x4) array

In [1]:
print("enter principle:")
P = int(input())
print("enter time:")
t = int(input())
print("enter rate:")
R = int(input())
a = P*(1+(R/100))*t
ci = a - P
print("Compound Interest =",ci)

enter principle:
10000
enter time:
5
enter rate:
5
Compound Interest = 42500.0


In [34]:
c=list(map (str, input().split()))
d={}
for i in c:
  if i not in d:
    d[i]=1;
  else:
    d[i]+=1

for i in d.keys():
  print("key ",i,"percentage ",float(d[i]*100/len(c)))

darshan darshan
key  darshan percentage  100.0


In [3]:

def isPalindrome(n):
    rev = 0
    k = n
    while k > 0:
        rev = (rev << 1) | (k & 1)
        k = k >> 1          
    return n == rev
 
 
if __name__ == '__main__':
 
    n = int(input())  
 
    if isPalindrome(n):
        print(n, "is a palindrome")
    else:
        print(n, "is not a palindrome")
 

15
15 is a palindrome


In [31]:
 def check_divisible(number):
  temp = number
  while(temp > 0):
    digit = number % 10
    if (digit != 0 and number % digit==0):
      return False
    temp = temp // 10
  return True
num = int(input("ENTER A NUMBER : "))
if(check_divisible(num)):
  print("ALL THE DIGITS OF NUMBER",num,"DIVIDE IT")
else :
  print("ALL THE DIGITS OF NUMBER",num,"DONOT DIVIDE IT")

ENTER A NUMBER : 123
ALL THE DIGITS OF NUMBER 123 DONOT DIVIDE IT


In [11]:
li=[]
print("enter number of elements:")
n=int(input())
print("enter elements:")
for i in range(0,n):
  ele = int(input())
  li.append(ele)
li.sort()
print("Second Largest:")
print(li[n-2])

enter number of elements:
5
enter elements:
34
12
45
76
31
Second Largest:
45


Numpy Solutions


In [12]:
import numpy as np

array = np.random.rand(4, 5 ,2)
print("\n\n3D Array filled with random values : \n", array);



3D Array filled with random values : 
 [[[0.07458723 0.13672046]
  [0.20218942 0.03875503]
  [0.29711608 0.67644575]
  [0.036677   0.30665339]
  [0.67011567 0.52038428]]

 [[0.14423603 0.89017443]
  [0.40161661 0.99001262]
  [0.85517679 0.02143517]
  [0.70904155 0.0846849 ]
  [0.38997081 0.60898082]]

 [[0.71859009 0.19036503]
  [0.65756593 0.79201283]
  [0.74710945 0.1075881 ]
  [0.13850933 0.41817042]
  [0.42767889 0.62110701]]

 [[0.53485191 0.2652874 ]
  [0.694626   0.48478064]
  [0.73511347 0.47817966]
  [0.93040405 0.14820578]
  [0.84281508 0.80580224]]]


In [15]:
import numpy as np

array = np.random.rand(6)
print("1D Array filled with random values : \n", array);
array.reshape(2,3)

1D Array filled with random values : 
 [0.9714667  0.11470446 0.74607613 0.47721097 0.41947546 0.00571027]


array([[0.9714667 , 0.11470446, 0.74607613],
       [0.47721097, 0.41947546, 0.00571027]])

In [17]:
import numpy as np
temp = [11, 3, 21, 21,100]
F = np.array(temp)
print("F: ")
print(F)
print("C:") 
print(5*F/9 - 5*32/9)

F: 
[ 11   3  21  21 100]
C:
[-11.66666667 -16.11111111  -6.11111111  -6.11111111  37.77777778]


In [18]:
import numpy as np    

x = np.array([[ 11,3,4,2,1,7,6,5,9,8,0,1,10],
       [13,14,12,16,15,18,17,20,19,22,21,23]])
print("\nNumber of dimensions:")
print(x.ndim)
print("Number of elements:")
print(x.size)
print("Number of bytes for each element in the said array:")
print(x.itemsize) 


Original arrays:
[list([11, 3, 4, 2, 1, 7, 6, 5, 9, 8, 0, 1, 10])
 list([13, 14, 12, 16, 15, 18, 17, 20, 19, 22, 21, 23])]

Number of dimensions:
1
Number of elements:
2
Number of bytes for each element in the said array:
8


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  after removing the cwd from sys.path.


In [30]:
import numpy as np
arr = [1,2,3,4,5,6,7,8,9,10,11,12]
array = np.array(arr)
array=array.reshape(3,4)
print("Original array:")
print(arr)
print("expected data:")
print(array)
print(array[0:2, 1:3])

Original array:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
expected data:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
