## **Label Encoder**


In [1]:
import numpy as np
from sklearn import preprocessing
encoder= preprocessing.LabelEncoder()

In [8]:
y=np.array(["Apple", "apple", "apple", "orange","orange"])

In [9]:
yencode1=encoder.fit(y)
list(yencode1.classes_)

['Apple', 'apple', 'orange']

In [10]:
yencode=encoder.fit_transform(y)

In [11]:
print(yencode)


[0 1 1 2 2]


## **Ordinal Encoder**

In [21]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X = [['Male'], ['Female'], ['Female'],['others'],['others']]
print(X)

[['Male'], ['Female'], ['Female'], ['others'], ['others']]


In [22]:
enc.fit(X)
list(enc.categories_)

[array(['Female', 'Male', 'others'], dtype=object)]

In [35]:
ord=enc.transform(X)

In [36]:
print(ord)

[[1.]
 [0.]
 [0.]
 [2.]
 [2.]]


## **Onehot Encoder**

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
y=(["Apple"], ["apple"], ["apple"], ["orange"],["orange"])
oneenc=OneHotEncoder()

In [43]:
oneenc.fit(y)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [49]:
out=oneenc.transform(y).toarray()

In [50]:
print(out)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [54]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
print(data)
print("Mean",np.mean(data))

[[0, 0], [0, 0], [1, 1], [1, 1]]
Mean 0.5


In [55]:
scaler = StandardScaler()
print(scaler.fit(data))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [56]:
 print(scaler.mean_)


[0.5 0.5]


In [58]:
transformeddata=scaler.transform(data)
print(transformeddata)

[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
